name: GitHub Profile Summary Cards

on:
  push:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config --global user.email "sarraayed124@gmail.com"
          git config --global user.name "Sarayed"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate GitHub profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ secrets.GH_TOKEN }}
          EXCLUDE: languages
          AUTO_PUSH: true
          BRANCH_NAME: main
          UTC_OFFSET: 0
